DROP DATABASE IF EXISTS login;
  CREATE DATABASE login;
  DROP TABLE IF EXISTS usuarios;
  CREATE TABLE usuarios (id INT(11)NOT NULL AUTO_INCREMENT,name VARCHAR (20),pass VARCHAR(50),PRIMARY KEY (id));
